"""English (API-Football) → Russian national team names, for bot output.
Mirrors frontend/src/utils/countries.ts. Canonical stored name stays English."""

# (russian, [english canonical + aliases])
_TEAMS: list[tuple[str, list[str]]] = [
    ("Бразилия", ["Brazil"]),
    ("Аргентина", ["Argentina"]),
    ("Франция", ["France"]),
    ("Англия", ["England"]),
    ("Испания", ["Spain"]),
    ("Германия", ["Germany"]),
    ("Португалия", ["Portugal"]),
    ("Нидерланды", ["Netherlands"]),
    ("Бельгия", ["Belgium"]),
    ("Италия", ["Italy"]),
    ("Хорватия", ["Croatia"]),
    ("Уругвай", ["Uruguay"]),
    ("Колумбия", ["Colombia"]),
    ("Мексика", ["Mexico"]),
    ("США", ["USA", "United States", "United States of America"]),
    ("Канада", ["Canada"]),
    ("Япония", ["Japan"]),
    ("Южная Корея", ["South Korea", "Korea Republic"]),
    ("Австралия", ["Australia"]),
    ("Марокко", ["Morocco"]),
    ("Сенегал", ["Senegal"]),
    ("Гана", ["Ghana"]),
    ("Нигерия", ["Nigeria"]),
    ("Камерун", ["Cameroon"]),
    ("Египет", ["Egypt"]),
    ("Алжир", ["Algeria"]),
    ("Тунис", ["Tunisia"]),
    ("Кот-д’Ивуар", ["Ivory Coast", "Côte d'Ivoire", "Cote d'Ivoire"]),
    ("Швейцария", ["Switzerland"]),
    ("Дания", ["Denmark"]),
    ("Швеция", ["Sweden"]),
    ("Польша", ["Poland"]),
    ("Сербия", ["Serbia"]),
    ("Уэльс", ["Wales"]),
    ("Шотландия", ["Scotland"]),
    ("Австрия", ["Austria"]),
    ("Украина", ["Ukraine"]),
    ("Чехия", ["Czech Republic", "Czechia"]),
    ("Турция", ["Turkey", "Türkiye", "Turkiye"]),
    ("Греция", ["Greece"]),
    ("Норвегия", ["Norway"]),
    ("Венгрия", ["Hungary"]),
    ("Россия", ["Russia"]),
    ("Иран", ["Iran", "IR Iran"]),
    ("Саудовская Аравия", ["Saudi Arabia"]),
    ("Катар", ["Qatar"]),
    ("Ирак", ["Iraq"]),
    ("ОАЭ", ["UAE", "United Arab Emirates"]),
    ("Эквадор", ["Ecuador"]),
    ("Перу", ["Peru"]),
    ("Чили", ["Chile"]),
    ("Парагвай", ["Paraguay"]),
    ("Боливия", ["Bolivia"]),
    ("Венесуэла", ["Venezuela"]),
    ("Коста-Рика", ["Costa Rica"]),
    ("Панама", ["Panama"]),
    ("Ямайка", ["Jamaica"]),
    ("Гондурас", ["Honduras"]),
    ("Новая Зеландия", ["New Zealand"]),
    ("Мали", ["Mali"]),
    ("Буркина-Фасо", ["Burkina Faso"]),
    ("ДР Конго", ["DR Congo", "Congo DR", "Democratic Republic of the Congo"]),
    ("ЮАР", ["South Africa"]),
    ("Кабо-Верде", ["Cape Verde", "Cabo Verde", "Cape Verde Islands"]),
    ("Гаити", ["Haiti"]),
    ("Кюрасао", ["Curaçao", "Curacao"]),
    ("Габон", ["Gabon"]),
    ("Гвинея", ["Guinea"]),
    ("Ангола", ["Angola"]),
    ("Замбия", ["Zambia"]),
    ("Узбекистан", ["Uzbekistan"]),
    ("Иордания", ["Jordan"]),
    ("Оман", ["Oman"]),
    ("Китай", ["China", "China PR"]),
    ("Индия", ["India"]),
    ("Словения", ["Slovenia"]),
    ("Словакия", ["Slovakia"]),
    ("Румыния", ["Romania"]),
    ("Болгария", ["Bulgaria"]),
    ("Финляндия", ["Finland"]),
    ("Исландия", ["Iceland"]),
    ("Ирландия", ["Republic of Ireland", "Ireland"]),
    ("Северная Ирландия", ["Northern Ireland"]),
    ("Босния и Герцеговина", ["Bosnia and Herzegovina", "Bosnia", "Bosnia & Herzegovina"]),
    ("Албания", ["Albania"]),
    ("Северная Македония", ["North Macedonia"]),
    ("Черногория", ["Montenegro"]),
    ("Грузия", ["Georgia"]),
    ("Израиль", ["Israel"]),
    ("Казахстан", ["Kazakhstan"]),
]

_BY_NAME: dict[str, str] = {}
for _ru, _names in _TEAMS:
    _BY_NAME[_ru.lower()] = _ru
    for _n in _names:
        _BY_NAME[_n.lower()] = _ru


def team_ru(name: str | None) -> str:
    """Russian team name, falling back to the original string."""
    if not name:
        return ""
    return _BY_NAME.get(name.strip().lower(), name)
